language: python
env:
  global:
    - BUILD_TYPE=None  # deb, opk, win32, flatpak
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk
jobs:
  include:
#    WIP
#    - os: linux
#      dist: xenial
#      python: 3.5
#      env: BUILD_TYPE=deb
#    - os: linux
#      dist: bionic
#      python: 3.6
#      env: BUILD_TYPE=deb
#    - os: linux
#      dist: focal
#      python: 3.8
#      env:
#        - BUILD_TYPE=flatpak
    - os: linux
      dist: focal
      python: 3.8
      env:
        - BUILD_TYPE=deb
    - os: linux
      dist: focal
      python: 3.8
      env:
        - BUILD_TYPE=win32
    - os: linux
      dist: trusty
      python: 3.4
      language: android
      env: BUILD_TYPE=opk
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.5
          - android-23
    - os: linux
      dist: trusty
      python: 3.4
      language: android
      env: BUILD_TYPE=opk
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.5
          - android-23
virtualenv:
  system_site_packages: true
before_install:
  - mkdir build
  - if [ "$BUILD_TYPE" = "deb" ]; then buildconfig/prebuild_deb.sh ; fi
  - if [ "$BUILD_TYPE" = "opk" ]; then buildconfig/prebuild_opk.sh ; fi
  - if [ "$BUILD_TYPE" = "win32" ]; then buildconfig/prebuild_win32.sh ; fi
  - if [ "$BUILD_TYPE" = "flatpak" ]; then buildconfig/prebuild_flatpak.sh ; fi
script:
  - buildconfig/build_tarball.sh
  - if [ "$BUILD_TYPE" = "deb" ]; then buildconfig/build_deb.sh ; fi
  - if [ "$BUILD_TYPE" = "opk" ]; then buildconfig/build_opk.sh ; fi
  - if [ "$BUILD_TYPE" = "win32" ]; then buildconfig/build_win32.py ; fi
  - if [ "$BUILD_TYPE" = "flatpak" ]; then buildconfig/build_flatpak.sh ; fi
deploy:
  provider: releases
  api_key:
    secure: LbDce8fi3QChPRBzM36o7m26IdQ9PySPE6kKXnNK4KrpdzZ5gzBpc/ak4omWKcN5x2XFgzIH075ykEpKiYQP764hvYO3hGi+IcHEzW9A1FofP2Whl/qOLFpmA+afnhl7Uyw4Uo8mo27UUDwrPIrkjIlLW2PPUSiMDVhz6t28cQAsBXcMOBTrDuRFCtUHmkODFq6o6IEbkeoG7eVC/LFVLxO4zGHcxcJCyl6ar1GD9wznFxDomtyQiT7Xwxw9DpzHWUgdPCpYULBvTU+GBTMMQVKPZLROFwmdWy/VMCo9VfmITNNe0EBX7OQWel8CjIZAdqa04bWz23HiTvmvaPnWDYWykCUl/FEy9y6akl/aBhOLCtI2VeKO1jI6jYWQsjI+z4P1zcTBio/xfhwqk7E5a6OesmZLCwLSwyK9R8dtUYdCzp602hkPvxmyWA61gHtsPttROoLmaD+VLIVbvjmkohXqLp72vsgzDIFz59S+19DoBTUmh4kWVSWH9hrG72ynSwl+9RNHTbAlXCZhUNQktBNWCQSltAndyzNCjU0WCohmj2uFJDa0LyIOkE27G8BmwyQ+mRpOp8KByKgawUWXOjYPD5J1gs5X9fHtMdPKWbn4MIaQy66jBj0+lFwxwX2/5J7T3MuRRuxfHzw7GQS+MzrctgRF4s3c6mEAHypAK2Q=
  file_glob: true
  file: build/*
  on:
    repo: Tuxemon/Tuxemon
    branch: development
  skip_cleanup: true
