language: python
env:
  global:
    - BUILD_TYPE=None  # deb, opk, win32
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk
jobs:
  include:
#    - os: linux
#      dist: xenial
#      python: 3.5
#      env: BUILD_TYPE=deb
#    - os: linux
#      dist: bionic
#      python: 3.6
#      env: BUILD_TYPE=deb
    - os: linux
      dist: focal
      python: 3.8
      env:
        - BUILD_TYPE=deb
        - BUILD_TYPE=win32
    - os: linux
      dist: trusty
      python: 3.4
      language: android
      env: BUILD_TYPE=opk
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.5
          - android-23
    - os: linux
      dist: trusty
      python: 3.4
      language: android
      env: BUILD_TYPE=opk
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.5
          - android-23
virtualenv:
  system_site_packages: true
before_install:
  - mkdir build
  - if [ "$BUILD_TYPE" = "deb" ]; then buildconfig/prebuild_deb.sh ; fi
  - if [ "$BUILD_TYPE" = "win32" ]; then buildconfig/prebuild_win32.sh ; fi
script:
  - buildconfig/build_tarball.sh
  - if [ "$BUILD_TYPE" = "deb" ]; then buildconfig/build_deb.sh ; fi
  - if [ "$BUILD_TYPE" = "opk" ]; then buildconfig/build_opk.sh ; fi
  - if [ "$BUILD_TYPE" = "win32" ]; then python3 buildconfig/setup_win32.py build ; fi
deploy:
  provider: s3
  access_key_id: AKIAJCO54X2SZSP2HYCA
  secret_access_key:
    secure: IvdL4/le7EuQj7qepYWB4TcQAlkishk8k/B4Dxx2X7jmNSpFW8paoe/K+wTxNdbknikTgoUIqAbi93s8HczIlHPOdKPaCUVFr5YgaP5vRxu0AvSLMrs04ZdOpidVRSXHajGC7oCSe62TQf+lJbNJ/ZXUVjjNApPIPH46x45pZ1E3M3fwGn9bBVP7+ju8q7AZJqZIwalI24A4qk9jHUZoYUuOKToJmPAus9s4Lsp4xKAw3XTaJYdlWKZ/y5st+1+6a/8qBpBBifCYThWDIYq27BhNAK2W4Nvm8+YjYCbkYMpQxRXKZCl1YUO4RzpHcpYniNgKI0kwxWhY6lA9WeXcS98GldH5oJdaIvdorp1JQMU4pyom3FwOmwRMbIoKfKYKW7x9kjTmEzWg5pdfSEDYby1zVciEyjuVtqP1esEnhljMPlKEBjPVObfdz8mZSUcYss46k+y8Fgqfgkng0QP83YCVC8izTPJOCjfdCfn+tirbdMQbKk2MQ5eK0vFQlghgYc232LprJoPYVW6x5lNV25s9IZnppDd7zGo7DUe2ObKEZBzkmdAmM4RANnQrbzr+SEuKA9gbAUnlrpBNK+n1NkdJn7ya1JynvbyiIG5+JfY9Z4R00gHOUu+/Hy3bMg++QnGoSdipn2M9M6NBvzerpqzg754XL6q5pzNM7XmoG5c=
  bucket: tuxemon
  skip_cleanup: true
  acl: 'public_read'
  local_dir: build
  on:
    repo: Tuxemon/Tuxemon
    branch: development
